### ISSUE TITLE
Question: Incoming PINGREQ

### ISSUE THREAD

**Issue by f0rr0** [Nerixyz/mqtts#28]
Hi, 

I am using `mqtts` in Facebook Messenger to connect with the broker. I noticed that the broker is sending `PINGREQ` to the client. According to what I know, `PINGREQ` is only meant to be sent to broker from client and not the other way round. I was wondering if you have noticed the same behaviour while working with Instagram for example and if you have any thoughts on this.

Thanks

**Comment by f0rr0** [comment]
In further research I found out that Paho client implements sending `PINGRESP` and handles receiving `PINGREQ`

https://github.com/eclipse/paho.mqtt.python/blob/9c22a9c297c0cdc4e1aac13aa19073e09a822961/src/paho/mqtt/client.py#L2464-L2466

**Comment by Nerixyz** [comment]
It's not spec compliant. 
> The PINGREQ Packet is sent from a Client to the Server.

For these servers you'd generally want to extend the client. In this case however, it's fine to include it in the main library as it doesn't break anything.
